version: '3'
services:
  api:
    container_name: api
    build:
      context: ./build/api
      dockerfile: Dockerfile
    volumes:
      - ./api:/go/src/github.com/LiveSchedule-v2
    tty: true
    environment:
      - TZ=Asia/Tokyo