version: '3'
services:
  api:
    container_name: api
    build:
      context: ./build/api
      dockerfile: Dockerfile
    volumes:
      - ./api:/go/src/github.com/LiveSchedule-v2
    ports:
      - 8000:8000
    tty: true
    environment:
      - TZ=Asia/Tokyo
  
  db:
    container_name: ${DB_HOST}
    build:
      context: ./build/db
      dockerfile: Dockerfile
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

volumes:
  db-store:
